# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  demirorencaseidentityserver:
    image: demirorencaseidentityserver
    build:
      context: .
      dockerfile: DemirorenCase.IdentityServer/Dockerfile
    ports:
      - 7016
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
