# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  demirorencaseloggerworkerservice:
    image: demirorencaseloggerworkerservice
    build:
      context: .
      dockerfile: DemirorenCase.LoggerWorkerService/Dockerfile
    ports:
      - 2018
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
